### ISSUE TITLE
Die Übersetzung wurde automatisch gesperrt, aufgrund folgender Hinweise: Das Repository konnte nicht zusammengeführt werden.

### ISSUE THREAD

**Issue by sbormann** [ioBrokerTranslator/doc#2]
Hi,
iqontrol wurde in weblate gesperrt und ich bekomme es nicht wieder entsperrt. Kann mir jemand dabei helfen?

Fehlermeldung:
```
Das Repository konnte nicht zusammengeführt werden.
Weblate konnte Upstream-Änderungen während der Aktualisierung des Repositorys nicht zusammenführen.

First, rewinding head to replay your work on top of it...
Applying: Update index_m.js
Using index info to reconstruct a base tree...
M	admin/index_m.js
Falling back to patching base and 3-way merge...
Auto-merging admin/index_m.js
CONFLICT (content): Merge conflict in admin/index_m.js
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 Update index_m.js

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Comment by UncleSamSwiss** [comment]
Weblate beschreibt sehr schön, was zu machen ist (den ersten und den letzten Schritt kannst du weglassen):

1. Add Weblate exported repository as a remote.
`git remote add weblate https://weblate.iobroker.net/git/adapters/iqontrol/ ; git remote update weblate`
2. Merge Weblate changes and resolve any conflicts.
`git merge weblate/main`
3. Push changes into upstream repository.
`git push origin main`

Um von Weblate Git pullen zu können, musst du deinen API Key und den Benutzer von Weblate benutzen.

**Comment by Apollon77** [comment]
@sbormann Do you still need help (asking because I see it is still/again blocked)? I now unblocked some ... how can I help? Just contact me in telegram or discord

**Comment by sbormann** [comment]
Hi Ingo, thank you for that! At the moment i have absolutely no time left to work on iqontrol, but i will try again if i have more time.
